### ISSUE TITLE
Flurl.Signed 3.0.5 and Flurl.Http.Signed 3.2.3?

### ISSUE THREAD

**Issue by stogle** [ellenfieldn/Flurl.Signed#10]
Hi @ellenfieldn, as with the last couple of issues I submitted, I'm requesting new releases of Flurl.Signed and Flurl.Http.Signed corresponding to the latest Flurl 3.0.5 and Flurl.Http 3.2.3 releases. We really need the fix for https://github.com/tmenier/Flurl/pull/642, which was released in [Flurl.Http 3.2.1](https://github.com/tmenier/Flurl/releases/tag/Flurl.Http.3.2.1) but we will take the opportunity to jump to the latest version.

Hopefully this is as simple to resolve as [last time](https://github.com/ellenfieldn/Flurl.Signed/issues/9#issuecomment-786279443)? Thank you again for your efforts.

**Comment by ellenfieldn** [comment]
Hey, sorry! I'll get it running again. Looks like I have a few hoops to jump through, but it shouldn't be too bad. Worst case scenario, I can fall-back to a manual build for this version while I get it sorted out.

**Comment by ellenfieldn** [comment]
That wasn't too bad. They're indexing on nuget.org and should be available soon. Let me know if it works! :)

**Comment by stogle** [comment]
Glad to hear from you! We've update our code and are just running this version through its paces. Looks good so far.

**Comment by ellenfieldn** [comment]
Awesome! I'll close this issue for now, but let me know if you hit any issues.
