### ISSUE TITLE
Respectfully request creating Flurl.Signed and Flurl.HTTP.Signed for the latest Flurl version

### ISSUE THREAD

**Issue by astrohart** [ellenfieldn/Flurl.Signed#11]
@ellenfieldn FYI, the `Flurl` and `Flurl.Http` NuGet packages are distributed at version `4.0.0` but the `Flurl.Signed` NuGet package is still at v`3.0.6`, and the `Flurl.Http.Signed` NuGet package is still at `3.2.4`.  

Please move the *.Signed packages to `4.0.0`.  Thanks!

**Comment by ellenfieldn** [comment]
Sorry for the long delay! I just saw this today and after some fixing some issues with the build scripts, pushed the new versions of Flurl.Signed and Flurl.HTTP.Signed.
