### ISSUE TITLE
create new signing cert

### ISSUE THREAD

**Issue by ellenfieldn** [ellenfieldn/Flurl.Signed#4]
the old cert expired

**Comment by ellenfieldn** [comment]
Going to get a real signing certificate this time rather than using a self-signed cert.

**Comment by ellenfieldn** [comment]
Planning to address this in the next week or so...

Timeframe depends on how long it takes me to select a CA that supports exportable keys (can't use it for automation otherwise) and is affordable, plus however long it takes them to do the identity vetting process.

**Comment by tmenier** [comment]
Have you looked at https://letsencrypt.org? It's completely free and very reputable, but I'm not super knowledgeable in this area so I'm not certain if it meets the requirements.

**Comment by ellenfieldn** [comment]
Weird. I thought I had responded to this, but I guess I never submitted it.

Unfortunately, I can't use letsencrypt because they don't support generating code-signing certificates. 

I've selected a CA and have begun the process of getting a certificate. It's been a little more challenging than I thought. Now that I've sorted through a few technical issues I have to find a notary and submit a bunch of notarized paperwork to verify my identity, but hopefully I'll be able to get this done within the next week.

**Comment by tmenier** [comment]
Ick. Thanks for the effort, I honestly don't know that I would have moved forward with that. I've reached out to @jongalloway with the .NET Foundation to see if they can assist. I don't know, but I have to think there's a better way for OSS projects.
