### ISSUE TITLE
No signed version of Flurl 2.4.0

### ISSUE THREAD

**Issue by Jedmannen** [ellenfieldn/Flurl.Signed#5]
The latest published version of Flurl.Http.Signed (2.3.2) wants version 2.7.1 of Flurl , but the latest version of Flurl is 2.8.0. If you use the latest versions you will need to use assembly redirect directives.  A signed version of Flurl 2.4.0 is needed to avoid this, Flurl.Http 2.4.0 uses Flurl 2.8.0

**Comment by ellenfieldn** [comment]
Hey, sorry, I totally didn't see this. I'll be working on getting the signed assemblies going again. 

The way the automated script currently works is that it just signs the latest versions of Flurl.Http and Flurl. Would you need any of the intermediate versions to be signed as well? 

I can do them -- it'll just be a manual process.

**Comment by ellenfieldn** [comment]
Tracking in #6
