### ISSUE TITLE
Any chance of a Flurl.Signed 2.8.2?

### ISSUE THREAD

**Issue by stogle** [ellenfieldn/Flurl.Signed#6]
Hi. Thank you for your efforts. I see the latest version on NuGet is Flurl.Signed 2.8.0. Would it be possible to have a signed version of the Flurl 2.8.2 release?

**Comment by ellenfieldn** [comment]
Hey, I realize that I'm way late in responding to this (Sorry!), but It's unlikely. The requirements for signing the packages and publishing to nuget.org has changed and requires a code-signing certificate, which tend to be kinda pricey.

I could maybe look into publishing them to an alternative package source like MyGet if that would help?

**Comment by stogle** [comment]
Since, the [other issue](https://github.com/tmenier/Flurl/issues/39) is more popular perhaps this can be closed? I [replied there](https://github.com/tmenier/Flurl/issues/39#issuecomment-702929219).

**Comment by ellenfieldn** [comment]
Closing since the issue is fixed
