### ISSUE TITLE
Flurl.Signed 3.0.1?

### ISSUE THREAD

**Issue by stogle** [ellenfieldn/Flurl.Signed#9]
Hi @ellenfieldn, it's me again. I created #6 last October and after some discussion there and in tmenier/Flurl#39 you managed to make [Flurl.Signed 2.8.2](https://www.nuget.org/packages/Flurl/2.8.2) and [Flurl.Http.Signed 2.4.2](https://www.nuget.org/packages/Flurl.Http.Signed/2.4.2) available on NuGet. And shortly after that when Flurl and Flurl.Http 3.0.0 were released, [Flurl.Signed 3.0.0](https://www.nuget.org/packages/Flurl.Signed/3.0.0) and [Flurl.Http.Signed 3.0.0](https://www.nuget.org/packages/Flurl.Http.Signed/3.0.0) followed, and all was good.

But now, Flurl 3.0.1 and Flurl.Http 3.0.1 have been available for a couple of months and there's be no "sign" of the signed versions. Are new versions still supposed to be published automatically?

**Comment by ellenfieldn** [comment]
Hey, Sorry!

Turns out if I don't log into my personal Azure Devops subscription often enough, the scheduled builds don't run. I'll get it up ASAP!

**Comment by ellenfieldn** [comment]
Ok. Should be up. Give it a whirl!

**Comment by stogle** [comment]
Great! I'm glad it was a simple fix. I see it on NuGet.org and will give it a try as soon as I can.

**Comment by stogle** [comment]
Looks good!

**Comment by ellenfieldn** [comment]
Great! I'll close this issue then.

Let me know if you have any other issues!
